GET http://localhost:8080/api/todos
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im81NFpXYXIwRkVhdm1UcXNnU1hPRyJ9.eyJpc3MiOiJodHRwczovL2Zyb2xhbmQtcHJvamludC1tMS0yMjIzLXNhbmRib3guZXUuYXV0aDAuY29tLyIsInN1YiI6IjFjNlB6WXBwM09TVjNSSEpheVBVQjJYcFNmdW9lMmpXQGNsaWVudHMiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBpIiwiaWF0IjoxNjg2NTAxNDc5LCJleHAiOjE2ODY1ODc4NzksImF6cCI6IjFjNlB6WXBwM09TVjNSSEpheVBVQjJYcFNmdW9lMmpXIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.1q0OyGdoYfHKc3e54eNqLnd_uMcNHnZ7RAyZ4mznoFm9G2ms8DPB7gJ-9P01VXag7f7yJJzxfU305tnbV0c8NrHjsRZ0UEA8UQVpQui_QB6mN8X8MxSjKeR15ObFHRiDBFXUmgVHu2Mu_IZ8gZYhtuLxD-SVdxyuba8dvANN7uIwx_Uazf-ue104xRqwxGvheQvFUzPABBVC61VZNll4Fuwb9ui1VObPoZH1eGB64uHAsM_9j9_dOjzvM3O4_NgYH7SAsxBHG0KKCSnkYsbeO81yIYsphUrG35LxoTeZKNVhnH-k7WJu73VMoDipqE2fSKwSxJ5Zgu4NY-f7bI2lzQ

###
