GET http://localhost:8080/api/todos
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkJ6RHB6S1otSTUyVjVnVl9tZ1NnNyJ9.eyJpc3MiOiJodHRwczovL3RlYWNoZXItcHJvamludC0yMjIzLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NDg3NDI3NGMzZGYwNjRjZWVjYmZlNDQiLCJhdWQiOlsiaHR0cHM6Ly90b2RvZGVtby9hcGkiLCJodHRwczovL3RlYWNoZXItcHJvamludC0yMjIzLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2ODY2MDA3MDEsImV4cCI6MTY4NjY4NzEwMSwiYXpwIjoibU5IUWtRb21FenhLUFNwbjlKVWRoSzNMTmFLUEpLMEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG9mZmxpbmVfYWNjZXNzIn0.Un-yoezVEfRFDU3gJiCTFsY5rmi_LdHYTyPcH9iJyKTqSzbAW3loo46WXz4-Cu4dTYzuRI8orenT0zifYkP-JEiCLtskKt9Ek_M9iH7qs6F1I1XHf5YH_sXy9uN-wprxAOFIbeYQx8Tqacy4nu6hb2r3aKEdMqYSYrGY94mMEYH-uksl3k2aIx54a2DmzOyK22tJlqnO9vH764PFZ5lMzp4HCt5M7_8RMBWxZ9pxhe_f-KC5LAG7LES2ZomRCIB1LIpNaKWpKoJokNvmc3BS_2GKohhxLp4yQpQjLcGZJRSTuYtRtSErmiyEUoEsBnqejJGTAFng3ZOOrsX8uopeRA

###
GET http://localhost:8080/api/todos/57e48b03-8e76-4019-95ea-0945ce9c1adb
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkJ6RHB6S1otSTUyVjVnVl9tZ1NnNyJ9.eyJpc3MiOiJodHRwczovL3RlYWNoZXItcHJvamludC0yMjIzLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NDg3NDI3NGMzZGYwNjRjZWVjYmZlNDQiLCJhdWQiOlsiaHR0cHM6Ly90b2RvZGVtby9hcGkiLCJodHRwczovL3RlYWNoZXItcHJvamludC0yMjIzLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2ODY2MDA3MDEsImV4cCI6MTY4NjY4NzEwMSwiYXpwIjoibU5IUWtRb21FenhLUFNwbjlKVWRoSzNMTmFLUEpLMEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG9mZmxpbmVfYWNjZXNzIn0.Un-yoezVEfRFDU3gJiCTFsY5rmi_LdHYTyPcH9iJyKTqSzbAW3loo46WXz4-Cu4dTYzuRI8orenT0zifYkP-JEiCLtskKt9Ek_M9iH7qs6F1I1XHf5YH_sXy9uN-wprxAOFIbeYQx8Tqacy4nu6hb2r3aKEdMqYSYrGY94mMEYH-uksl3k2aIx54a2DmzOyK22tJlqnO9vH764PFZ5lMzp4HCt5M7_8RMBWxZ9pxhe_f-KC5LAG7LES2ZomRCIB1LIpNaKWpKoJokNvmc3BS_2GKohhxLp4yQpQjLcGZJRSTuYtRtSErmiyEUoEsBnqejJGTAFng3ZOOrsX8uopeRA
